{
 "title": "SLIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status!~\"5..\"}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget Remaining",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min((1 - ((1 - sum(increase(http_requests_total{ status!~\"5..\"}[30d])) by (job) / sum(increase(http_requests_total[30d]))by (job))  / 0.005)) * 100, 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Burn Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(1 - (sum(rate(http_requests_total{status!~\"5..\"}[5m])) by (job) / sum(rate(http_requests_total[5m])) by (job))) / 0.005",
     "legendFormat": "5m (ultra-fast): {{job}}"
    },
    {
     "expr": "(1 - (sum(rate(http_requests_total{status!~\"5..\"}[1h])) by (job) / sum(rate(http_requests_total[1h])) by (job))) / 0.005",
     "legendFormat": "1h (fast burn): {{job}}"
    },
    {
     "expr": "(1 - (sum(rate(http_requests_total{status!~\"5..\"}[6h])) by (job) / sum(rate(http_requests_total[6h])) by (job))) / 0.005",
     "legendFormat": "6h (slow burn): {{job}}"
    },
    { "expr": "vector(14.4)", "legendFormat": "page (14.4×)" },
    { "expr": "vector(6)", "legendFormat": "ticket (6x)" },
    { "expr": "vector(1)", "legendFormat": "sustainable (1.0x)" }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_highr_seconds_bucket[5m])) by (le,job))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_highr_seconds_bucket[5m])) by (le,job))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}